language: python
python:
  - '3.7'
  - '3.6'
  - '3.5'
  - '3.4'

sudo: false

install:
  - pip install -r requirements_test.txt

script:
  - python -m black --check .
  - python -m pytest test/ --doctest-modules -v --cov xcomfort --cov-report term-missing
  - python -m pylint --errors-only --rcfile .pylint.rc xcomfort/*

after_success:
  - coveralls
